### PR TITLE
Add FedVSSL baseline

### PR DESCRIPTION
**Pull request by yasar-rehman**
## Issue 

https://github.com/adap/flower/issues/2058

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.dev/docs/writing-documentation.html)
- [ ] Update [changelog](https://github.com/adap/flower/blob/main/doc/source/changelog.rst)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.dev/join-slack/) (channel `#contributions`)

### CODE REVIEW

File: baselines/FedVSSL/README.md [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+url: https://arxiv.org/abs/2207.01975
+labels: [cross-device, videossl] # please add between 4 and 10 single-word (maybe two-words) labels (e.g. "system heterogeneity", "image classification", "asynchronous", "weight sharing", "cross-silo")
+dataset: [UCF-101] # list of datasets you include in your baseline
+---
+
+# Federated Self-supervised Learning for Video Understanding
+> Note: If you use this baseline in your work, please remember to cite the original authors of the paper as well as the Flower paper.
+
+
+**paper:** [https://arxiv.org/abs/2207.01975](https://arxiv.org/abs/2207.01975)
```
Comment (jafermarq) [inline baselines/FedVSSL/README.md:12]:
```suggestion
**paper:** [arxiv.org/abs/2207.01975](https://arxiv.org/abs/2207.01975)
```

File: baselines/FedVSSL/README.md [hunk 2]
```diff
@@ -0,0 +1,144 @@
+---
+title: Federated Self-supervised Learning for Video Understanding
+url: https://arxiv.org/abs/2207.01975
+labels: [cross-device, videossl] # please add between 4 and 10 single-word (maybe two-words) labels (e.g. "system heterogeneity", "image classification", "asynchronous", "weight sharing", "cross-silo")
+dataset: [UCF-101] # list of datasets you include in your baseline
```
Comment (jafermarq) [inline baselines/FedVSSL/README.md:5]:
```suggestion
labels: [cross-device, ssl, videossl]
dataset: [UCF-101]
```

File: baselines/FedVSSL/README.md [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+
+# run downstream fine-tuning with pre-trained SSL model
+python -m main --pre_training=False # this will run using the default settings.
+```
+
+To run using FedAvg:
+```bash
+# this will run FedAvg baseline
+# This is done so to match the experimental setup in the paper
+python -m main --fedavg=True
```
Comment (jafermarq) [inline baselines/FedVSSL/README.md:103]: The code should be run as `python -m <baseline_package_name>.main ...`

Comment (jafermarq) [reply baselines/FedVSSL/README.md:103]: This will require to adjust the imports in several of your python files. For instance in you `main.py` instead of `from strategy import FedVSSL` you'll do `from <package_name>.strategy import FedVSSL`

Comment (jafermarq) [reply baselines/FedVSSL/README.md:103]: As i mentioned earlier, please rename your baseline directory to `fedvssl`, in that way your package name will be `fedvssl`.

File: baselines/FedVSSL/pyproject.toml [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+aiohttp_cors = "0.7.0"
+aioredis = "1.3.1"
+alabaster = "0.7.12"
+argh = "0.26.2"
+astropy = "4.0.2"
+async_generator = "1.10"
+async-timeout = "3.0.1"
+atomicwrites = "1.4.0"
+backcall = "0.2.0"
+
```
Comment (jafermarq) [inline baselines/FedVSSL/pyproject.toml:57]: A few packages were missing. I added them to the `pyproject.toml` as:
```
mmcv = "1.2.4"
mmengine = "0.8.4"
```

**Review by jafermarq — COMMENTED** [review]
Hi @yasar-rehman,

I've done only a initial pass through the baseline and left some comments. In addition to those:
* Please remove the `EXTENDED_README.md` file, that was intended only for you to use as a guide to make your baseline.
* I think it would be better to name your baseline as fedvssl (so with lowercase text). Please make sure that's reflected in the `pyproject.toml` right under `[tool.poetry]`. I think renaming the subdirectory to `fedvssl` and then creating an empty `__init__.py` inside should do it. Please use the same name for your top-level directory
* Could you replace the python configs with `Hydra` configs? 
* Could you rename the `docs` directory to `_static`? 
* Do we need the `requirements.txt`? it isn't mentioned anywhere in the readme. remove if not needed.
* Please run the formatting and test scripts. You'll likely be suggested to change many things (including many unused imports)
* Any chance we can raise the pytorch version to a more recent one (1.7.1 is fairly old -- from 2020). If you could make some small checks to see if a more recent (e.g. 1.13.1) works, that would be great. 

Overall i think this needs a bit of work still. Happy to sync with you and/or Yan over a call if some help is needed

File: baselines/FedVSSL/pyproject.toml [hunk 5]
```diff
@@ -0,0 +1,149 @@
...
+aiohttp = "3.7.4.post0"
+aiohttp_cors = "0.7.0"
+aioredis = "1.3.1"
+alabaster = "0.7.12"
+argh = "0.26.2"
+astropy = "4.0.2"
+async_generator = "1.10"
+async-timeout = "3.0.1"
+atomicwrites = "1.4.0"
+backcall = "0.2.0"
```
[the remark this answers is not in the document]
Comment (jafermarq) [reply baselines/FedVSSL/pyproject.toml:56]: I think it doesn't need to be part of the `pyproject.toml`.

File: baselines/fedvssl/README.md [hunk 6]
```diff
@@ -0,0 +1,168 @@
...
+poetry install
+
+# activate the environment
+poetry shell
+
+# install PyTorch with GPU support.
+pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
+
+# install mmcv package
+pip install mmcv==1.2.4
```
Comment (jafermarq) [inline baselines/fedvssl/README.md:77]:
```suggestion
pip install mmcv-full==1.2.4 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
pip install numpy==1.21.0
pip install tensorboard
pip install mmengine==0.8.4
```

Comment (jafermarq) [reply baselines/fedvssl/README.md:77]: as indicated by @yan-gao-GY to me over slack. please add it here

File: baselines/fedvssl/fedvssl/conf/base.yaml [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+# this is the config that will be loaded as default by main.py
+# Please follow the provided structure (this will ensuring all baseline follow
+# a similar configuration structure and hence be easy to customise)
+
+
+### hyper-parameters for FL pre-training ###
+pre_training: false
+exp_name: fedvssl_results
+data_dir: /home/data1
+partition_dir: /home/data1/ucf101/annotations
```
Comment (jafermarq) [inline baselines/fedvssl/fedvssl/conf/base.yaml:11]:
```suggestion
data_dir: fedvssl/data
partition_dir: fedvssl/data/ucf101/annotations
```

Comment (jafermarq) [reply baselines/fedvssl/fedvssl/conf/base.yaml:11]: that should point to the data dir created when running `dataset_preparation.py`, right?

File: baselines/fedvssl/fedvssl/conf/base.yaml [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+# ray config
+cpus_per_client: 2
+gpus_per_client: 1
+include_dashboard: false
+
+
+### hyper-parameters for downstream fine-tuning ###
+exp_name_finetune: finetune_results
+cfg_path_finetune: fedvssl/CtP/configs/ctp/r3d_18_kinetics/finetune_ucf101.py
+pretrained_model_path: /home/data1/FVSSL_reproduce/flower/baselines/fedvssl/fedvssl_results/round-20-weights.array.npz
```
Comment (jafermarq) [inline baselines/fedvssl/fedvssl/conf/base.yaml:38]:
```suggestion
pretrained_model_path: null
```

Comment (jafermarq) [reply baselines/fedvssl/fedvssl/conf/base.yaml:38]: this should be left like this (which will be translated into python as `None`).

File: baselines/fedvssl/fedvssl/main.py [hunk 9]
```diff
@@ -0,0 +1,268 @@
...
+        # We provide certain federated pretrained model that can be easily downloaded
+        # from the following link: https://github.com/yasar-rehman/FEDVSSL
+        # here we gave an example with FedVSSL (alpha=0, beta=0) checkpoint file
+        # The files after federated pretraining are usually saved in .npz format.
+
+        pretrained = cfg.pretrained_model_path
+
+        # conversion of the .npz files to the .pth format.
+        # If the files are saved in .npz format
+        if pretrained.endswith(".npz"):
```
Comment (jafermarq) [inline baselines/fedvssl/fedvssl/main.py:182]:
```suggestion
        if pretrained and pretrained.endswith(".npz"):
```

File: baselines/fedvssl/README.md [hunk 10]
```diff
@@ -0,0 +1,168 @@
...
+
+cd ..
+```
+
+
+Finally, we can launch the training:
+
+```bash
+# run federated SSL training with FedVSSL
+python -m fedvssl.main pre_training=true # this will run using the default settings.
```
Comment (jafermarq) [inline baselines/fedvssl/README.md:100]: if readers are presented with this as the first command, I think it would be better if first it is mentioend that they need to download one of the checkpoints, and either update the path to it in the `conf/base.yaml` or pass it as:
```bash
python -m fedvssl.main pre_training=true pretrained_model_path=<CHECKPOINT>.npz
```

**Review by jafermarq — COMMENTED** [review]
Hi @yan-gao-GY and @yasar-rehman,

I have highlighted a few lines to change. Nothing major. the main plus is that i was able to build the environment (following the extra commands included in the suggestions below). But then i got stuck with an error showing errors of the form:

```
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=9869, ip=10.0.0.35, actor_id=90960949ab18237e2dcfa8b401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f118fe8dd30>)
TypeError: FormatCode() got an unexpected keyword argument 'verify'
```
With `verify` nowhere to be found in the repo. Maybe something in `utils.set_config_mmcv()` is the reason?

File: baselines/fedvssl/fedvssl/conf/base.yaml (hunk 7 above)
Comment (jafermarq) [reply baselines/fedvssl/fedvssl/conf/base.yaml:11]: further testing seems to suggest these should be instead:
```
data_dir: fedvssl/data
partition_dir: ucf101/annotations/client_distribution
```

File: baselines/fedvssl/fedvssl/main.py [hunk 11]
```diff
@@ -0,0 +1,268 @@
...
+
+        client_resources = {
+            "num_cpus": cfg.cpus_per_client,
+            "num_gpus": cfg.gpus_per_client,
+        }
+        base_work_dir = cfg.exp_name
+        rounds = cfg.rounds
+        data_dir = cfg.data_dir
+        partition_dir = cfg.partition_dir
+        num_gpus = cfg.gpus_per_client
```
Comment (jafermarq) [inline baselines/fedvssl/fedvssl/main.py:115]: this will create issues if `gpus_per_client` is set to less than 1.0 (e.g. if we want to pack 2 clients on the same gpu for instance with `gpus_per_client: 0.5`.

File: baselines/fedvssl/fedvssl/conf/base.yaml [hunk 12]
```diff
@@ -0,0 +1,44 @@
...
+  swbeta: 1
+  base_work_dir: fedvssl_results
+  fraction_fit: 1.0
+  min_fit_clients: 5
+  min_available_clients: 5
+  fedavg: false
+
+# ray config
+cpus_per_client: 2
+gpus_per_client: 1
```
Comment (jafermarq) [inline baselines/fedvssl/fedvssl/conf/base.yaml:31]: Please edit this to follow the format used in other baselines:
```
client_resources:
  num_gpus: 1.0
  num_cpus: 2
```

**Review by jafermarq — COMMENTED** [review]
A few extra comments.

File: baselines/fedvssl/README.md (hunk 10 above)
Comment (yan-gao-GY) [reply baselines/fedvssl/README.md:103]: The checkpoints are used for downstream fine-tuning. The command here is to run SSL pre-training on UCF-101 dataset from scratch.

To run fine-tuning:
`python -m fedvssl.main pre_training=false pretrained_model_path=<CHECKPOINT>.npz`
The `pretrained_model_path` can be set to the checkpoints path trained by users on UCF-101 from scratch, or the downloaded ones which were trained on K-100 dataset.

File: baselines/fedvssl/fedvssl/conf/base.yaml (hunk 12 above)
Comment (yan-gao-GY) [reply baselines/fedvssl/fedvssl/conf/base.yaml:31]: Solved!

**Comment by yasar-rehman** [comment]
> A few extra comments below.
> 
> ALso, should it be indiated in the `README.md` that the `fedvssl_results` directory should be deleted between runs? should we make it go to the `outpts/` directory automatically generated by hydra (where the log is created).

It's better to not delete the fedvssl_results directory as it contains the global model checkpoints and the local training history of the clients. This might be important if someone wants to, let's say, evaluate the performance of the global model after every round or observe the local training history of the clients.

File: baselines/fedvssl/fedvssl/main.py (hunk 11 above)
Comment (yasar-rehman) [reply baselines/fedvssl/fedvssl/main.py]: @yan-gao-GY   

`num_gpus = int(np.ceil(cfg.client_resources.num_gpus))` # will resolve the issue.

File: baselines/fedvssl/pyproject.toml [hunk 13]
```diff
@@ -0,0 +1,138 @@
...
+    "Topic :: Software Development :: Libraries",
+    "Topic :: Software Development :: Libraries :: Python Modules",
+    "Typing :: Typed",
+]
+
+[tool.poetry.dependencies]
+python = ">=3.8.15, <3.12.0"  # don't change this
+flwr = { extras = ["simulation"], version = "1.5.0" }
+hydra-core = "1.3.2" # don't change this
+
```
Comment (jafermarq) [inline baselines/fedvssl/pyproject.toml:43]:
```suggestion
torch = { url = "https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp39-cp39-linux_x86_64.whl"}
torchvision = { url = "https://download.pytorch.org/whl/cu110/torchvision-0.8.2%2Bcu110-cp39-cp39-linux_x86_64.whl"}
mmengine = "0.9.0"
tensorboard = "2.15.1"
numpy = "1.23.0"
```

File: baselines/fedvssl/pyproject.toml [hunk 14]
```diff
@@ -0,0 +1,138 @@
...
+    "Topic :: Scientific/Engineering :: Artificial Intelligence",
+    "Topic :: Scientific/Engineering :: Mathematics",
+    "Topic :: Software Development",
+    "Topic :: Software Development :: Libraries",
+    "Topic :: Software Development :: Libraries :: Python Modules",
+    "Typing :: Typed",
+]
+
+[tool.poetry.dependencies]
+python = ">=3.8.15, <3.12.0"  # don't change this
```
Comment (jafermarq) [inline baselines/fedvssl/pyproject.toml:40]:
```suggestion
python = ">=3.9, <3.12.0"  # don't change this
```

File: baselines/fedvssl/pyproject.toml (hunk 13 above)
Comment (jafermarq) [reply baselines/fedvssl/pyproject.toml:43]: Let's install everything except `mmcv-full` in one go

File: baselines/fedvssl/README.md [hunk 15]
```diff
@@ -0,0 +1,171 @@
...
+poetry shell
+
+# install PyTorch with GPU support.
+pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
+
+# install mmcv package
+pip install mmcv-full==1.2.4 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
+pip install numpy==1.21.0
+pip install tensorboard
+pip install mmengine==0.9.0
```
Comment (jafermarq) [inline baselines/fedvssl/README.md:80]:
```suggestion
# install mmcv package
pip install mmcv-full==1.2.4 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
```

Comment (jafermarq) [reply baselines/fedvssl/README.md:80]: everything else is in `pyproject.toml`

File: baselines/fedvssl/README.md [hunk 16]
```diff
@@ -0,0 +1,171 @@
...
+
+```bash
+# run federated SSL training with FedVSSL
+python -m fedvssl.main pre_training=true # this will run using the default settings.
+
+# you can override settings directly from the command line
+python -m fedvssl.main pre_training=true mix_coeff=1 rounds=100 # will set hyper-parameter alpha to 1 and the number of rounds to 100
+
+# run downstream fine-tuning with pre-trained SSL model
+python -m fedvssl.main pre_training=false pretrained_model_path=<CHECKPOINT>.npz # this will run using the default settings.
```
Comment (jafermarq) [inline baselines/fedvssl/README.md:109]: I'm unable to run this. Resulting in errors of the type:
`NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8`

Could you give details on the exact CUDA version you used and Ubuntu version? Flower baselines expect Ubuntu 22.04 (for which only CUDA 11.7+ is available irrc).

**Review by jafermarq — COMMENTED** [review]
Hi @yasar-rehman , @yan-gao-GY ,

Thanks for making those changes. I was able to run the pre-training with UCF-101. However, the finetuning doesn't work for me. I suspect is an incompatibility version due to be using old packages. Flower baselines expect Ubuntu 22.04 and Python 3.10+; all baselines merged so far meet these requirements. 

Could you confirm you were able to run the finetuning on Ubuntu 22.04? what CUDA version?

File: baselines/fedvssl/README.md (hunk 16 above)
Comment (yasar-rehman) [reply baselines/fedvssl/README.md:109]: @jafermarq We haven't tested that on Ubuntu 22.04. We tested it with the following configuration:
Ubuntu -- > VERSION="16.04.6 LTS (Xenial Xerus)
CUDA Version: 11.4

I will try with CUDA 11.7 to see if can reproduce the above error.

Comment (yasar-rehman) [reply baselines/fedvssl/README.md:103]: > I'm unable to run this. Resulting in errors of the type: `NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8`
> 
> Could you give details on the exact CUDA version you used and Ubuntu version? Flower baselines expect Ubuntu 22.04 (for which only CUDA 11.7+ is available irrc).

@jafermarq Did you get the above error during the FL-pertaining or fine-tuning stage?

Comment (jafermarq) [reply baselines/fedvssl/README.md:103]: @yasar-rehman only for the fine-tuning. I was able to run the pre-training with command:
```bash
python -m fedvssl.main pre_training=true
```

Comment (yasar-rehman) [reply baselines/fedvssl/README.md:103]: @jafermarq @yan-gao-GY OK so after many attempts,  finally I was able to run both the pertaining and fine-tuning. 

@yan-gao-GY! I believe these updated versions of mmcv and mmengine will solve your side's "ROI_align" issue. 

CUDA Version: 12.0
Linux: 20.04.6 


Please install the following packages and remove the old ones. 

1.  pip install mmcv-full==1.7.1 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html  (**Found this by chance**)
2. pip install torch==1.13.0+cu117 torchvision==0.14.0+cu117 torchaudio==0.13.0 --extra-index-url https://download.pytorch.org/whl/cu117  
3.  ypaf==0.40.1 (with version 0.40.2 I was getting the error: TypeError: FormatCode() got an unexpected keyword argument 'verify')
4. tensorboard without specifying any version
5. mmengine==0.10.0 

The mmcv-full==1.7.1, to the best of my knowledge, is the final latest version that can be used with the CtP repository in its current form. The new versions of the mmcv >=2.0.0 cannot be used with the current CtP repository because most of the functionality in mmengine > 0.10.0 has either been modified or removed. 

Let me know if you encounter any errors.

Comment (jafermarq) [reply baselines/fedvssl/README.md:103]: amazing! this seems to be working. I had to change the number of processes to `1` (instead of `4`) in the main (because i only have a single GPU. I'll look into this more carefully and add another review later today.

**Review by jafermarq — COMMENTED** [review]
Hi @yasar-rehman and @yan-gao-GY,

It's great news that I'm now able to run the finetuning stage. I can confirm this also works with Python3.10 and in Ubuntu 22 (which are required for the baselines).

I added a couple of comments below. First i shown how to update the `pyproject.toml` with the updated requirements. Then i encourage you to move the finetuning code outside of the `main.py`. I think it's better to show how people can run the commands directly on their terminals. Wouldn't that be better?

Also, i noted that if I have run a finetuning and then I run another, the second will see the results of the first and report those without doing any work. This should be fixed. One easy way is to ensure all results (also for pretraining) are stored in the directory that `hydra` creates each time you run an experiment. 

Best,
Javier

File: baselines/fedvssl/fedvssl/main.py [hunk 17]
```diff
@@ -0,0 +1,268 @@
...
+        # start simulation
+        fl.simulation.start_simulation(
+            client_fn=client_fn,
+            num_clients=cfg.pool_size,
+            client_resources=client_resources,
+            config=fl.server.ServerConfig(num_rounds=cfg.rounds),
+            strategy=strategy,
+            ray_init_args=ray_config,
+        )
+    else:
```
[the remark this answers is not in the document]
Comment (yasar-rehman) [reply baselines/fedvssl/fedvssl/main.py]: Thank you for this suggestion. We've made the suggested changes.

The fine-tuning logic is now decoupled from the main.py.

An additional Python file with the name` finetune_preprocess.py` is added to preprocess the global weights stored as `.npz` file. 
The subprocess. run() logic is removed. 

we've added the necessary instructions as follows to run the fine-tuning:
**Training:**
`bash fedvssl/CtP/tools/dist_train.sh fedvssl/conf/mmcv_conf/finetuning/r3d_18_ucf101/finetune_ucf101.py 1 --work_dir=./finetune_results --data_dir=fedvssl/data`
**Testing:**
`bash fedvssl/CtP/tools/dist_test.sh fedvssl/conf/mmcv_conf/finetuning/r3d_18_ucf101/test_ucf101.py 1 --work_dir=./finetune_results --data_dir=fedvssl/data --progress`

File: baselines/fedvssl/fedvssl/main.py [hunk 18]
```diff
@@ -0,0 +1,268 @@
...
+
+        with open(cfg_path, "w") as f_w:
+            f_w.write(config_content)
+
+        subprocess.run(
+            [
+                "bash",
+                f"{cfg.dist_train_path}",
+                f"{cfg_path}",
+                "4",
```
[the remark this answers is not in the document]
Comment (yasar-rehman) [reply baselines/fedvssl/fedvssl/main.py]: The number of GPUs is now user-defined during the fine-tuning stage:

Training:
bash fedvssl/CtP/tools/dist_train.sh fedvssl/conf/mmcv_conf/finetuning/r3d_18_ucf101/finetune_ucf101.py 1 --work_dir=./finetune_results --data_dir=fedvssl/data
Testing:
bash fedvssl/CtP/tools/dist_test.sh fedvssl/conf/mmcv_conf/finetuning/r3d_18_ucf101/test_ucf101.py 1 --work_dir=./finetune_results --data_dir=fedvssl/data --progress

**Review by jafermarq — COMMENTED** [review]
Hi @yasar-rehman, @yan-gao-GY 

This is looking good. I was able to run the experiments fine. Interestingly i got much better results for UCF-101 results when pretraining on UCF-101 than those in the table... 

Could you take some time to address the comments below?

File: baselines/fedvssl/fedvssl/client.py [hunk 19]
```diff
@@ -0,0 +1,135 @@
...
+                num = int("".join(file_item.split(".")[0].split("_")))
+                log_f_list.append((file_item, num))
+
+        # take the last log file
+        log_f_list.sort(key=lambda x: x[1])
+        log_f_name = work_dir + "/" + log_f_list[-1][0]
+        loss_list = []
+        with open(log_f_name, "r") as f_r:
+            for line in f_r.readlines():
+                line_dict = eval(line.strip())
```
[the remark this answers is not in the document]
Comment (yan-gao-GY) [reply baselines/fedvssl/fedvssl/client.py:108]: yes it's correct to enable a python dict

File: baselines/fedvssl/README.md [hunk 20]
```diff
@@ -0,0 +1,222 @@
...
+After that, we perform the test process:
+
+```bash
+bash fedvssl/CtP/tools/dist_test.sh fedvssl/conf/mmcv_conf/finetuning/r3d_18_ucf101/test_ucf101.py 1 --work_dir=./finetune_results --data_dir=fedvssl/data --progress
+```
+
+## Expected results
+
+### Pre-training and fine-tuning on UCF-101
+The pre-training in the paper was conducted on Kinectics-400, which takes a considerable amount of time without access to server-grade hardware.
```
[the remark this answers is not in the document]
Comment (yan-gao-GY) [reply baselines/fedvssl/README.md:185]: solved

File: baselines/fedvssl/README.md [hunk 21]
```diff
@@ -0,0 +1,222 @@
...
+
+**Contributers:** Yasar Abbas Ur Rehman and Yan Gao
+
+## Experimental Setup
+
+**Task:** Action Recognition
+
+**Model:** 
+* This directory first pretrain Catch-the-Patch (CtP) model from the CtP (see `CtP/pyvrl/models/pretraining/ctp`) repository during FL pretrainin stage The backbone model is R3D-18 (see `/CtP/pyvrl/models/backbones/r3d.py`). 
+* After pretraining it finetunes the R3D-18 model on UCF-101 dataset.
```
[the remark this answers is not in the document]
Comment (yan-gao-GY) [reply baselines/fedvssl/README.md]: solved

**Review by jafermarq — COMMENTED** [review]
Hi @yasar-rehman , @yan-gao-GY ,

This baseline can be merged 🥳 . But first, could you look at the comment i left below? Ping me when ready.

**Comment by yan-gao-GY** [comment]
@jafermarq thanks for your recent fix! It would take ~1 day if using 6 RTX 3090. Let's change the statement n the `Expected Results` section to keep consistent?

**Review by jafermarq — APPROVED** [review]
@yan-gao-GY , @yasar-rehman ,

Your `FedVSSL` baseline is ready to be merged. Many thanks for thanks for the hard work !

**Review by danieljanes — APPROVED** [review]
